version: '3.3'
services:
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=0000
      - POSTGRES_USER=postgres
      - POSTGRES_DB=coffee_shop

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    restart: always