package ru.popova.practice.shop.util.constants;

public interface NumConstants {

    int NUMBER_OF_ELEMENTS_ON_PAGE = 9;

    int MIN_NUMBER_OF_LETTERS_IN_TOPPING_NAME = 3;

    int MAX_NUMBER_OF_LETTERS_IN_TOPPING_NAME = 40;

    int MIN_TOPPING_PRICE = 0;

    int MAX_TOPPING_PRICE = 100;

    int MIN_NUMBER_OF_LETTERS_IN_DRINK_NAME = 3;

    int MAX_NUMBER_OF_LETTERS_IN_DRINK_NAME = 20;

    int MIN_DRINK_PRICE = 10;

    int MAX_DRINK_PRICE = 999;

    int MIN_DRINK_VOLUME = 49;

    int MAX_DRINK_VOLUME = 999;

    int MIN_NUMBER_OF_LETTERS_IN_DRINK_DESCRIPTION = 2;

    int MAX_NUMBER_OF_LETTERS_IN_DRINK_DESCRIPTION = 300;

    int MIN_CATEGORIES_NUM = 1;

    int MAX_CATEGORIES_NUM = 5;

    int MAX_NUMBER_OF_IMAGES = 3;

    int MIN_FULL_NAME_LENGTH = 3;

    int MAX_FULL_NAME_LENGTH = 100;

    int MIN_PHONE_NUMBER_LENGTH = 7;

    int MAX_PHONE_NUMBER_LENGTH = 11;

}
